config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index', as: :home

  get '/blog/:slug-:id', to: 'articles#show', as: :article

  match "/login", to: 'user#login', as: 'login_user', via: [:get, :post]
  get '/logout', to: 'user#logout', as: 'logout_user'
  get '/register', to: 'user#new', as: 'new_user'
  post '/register', to: 'user#create'

  get '/draft', to: 'articles#index', as: :articles
  get '/draft/new', to: 'articles#new', as: :new_article
  post '/draft/new', to: 'articles#create'

  get '/draft/:id/edit', to: 'articles#edit', as: :edit_article
  patch '/draft/:id/edit', to: 'articles#update'
  get '/draft/:id/delete', to: 'articles#delete', as: :delete_article
end

app/views/elements/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= url_for('/') %>">Brand</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="welcome">
            <span>Bonjour,</span> <%= link_to user_current.username, '#', :class => 'user_trigger', :'data-username' => user_current.username %>
          </li>
        <% else %>
          <% if current_page? new_user_path %>
            <li class="active">
          <% else %>
            <li>
          <% end %>
              <%= link_to "S'inscrire", new_user_path %>
            </li>
          <% if current_page? login_user_path %>
            <li class="active">
          <% else %>
            <li>
          <% end %>
              <%= link_to 'Se connecter', login_user_path %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>