config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index', as: :home

  get '/blog/:slug-:id', to: 'articles#show', as: :article

  match "/login", to: 'user#login', as: 'login_user', via: [:get, :post]
  get '/logout', to: 'user#logout', as: 'logout_user'
  get '/register', to: 'user#new', as: 'new_user'
  post '/register', to: 'user#create'

  get '/draft', to: 'articles#index', as: :articles
  get '/draft/new', to: 'articles#new', as: :new_article
  post '/draft/new', to: 'articles#create'

  get '/draft/:id/edit', to: 'articles#edit', as: :edit_article
  patch '/draft/:id/edit', to: 'articles#update'
  get '/draft/:id/delete', to: 'articles#delete', as: :delete_article
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true, uniqueness: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    logged_in
    if user_current.role != 'admin'
      @draft = Article.friendly.where(:user_id => user_current.id)
    else
      @draft = Article.friendly.all
    end
  end

  def show
    @article = Article.friendly.where(:published => true).find(params[:id])
    if params[:slug] != @article.slug
      redirect_to article_path(@article.slug, @article.id)
    end
  end

  def new
    logged_in
    @draft = Article.new
  end

  def create
    @draft = Article.new(article_params)

    if @draft.save
      @draft.update_attributes(:user_id => user_current.id)
      flash[:success] = "Le brouillon a bien été créer"
      redirect_to articles_path
    else
      flash[:error] = "Corriger vos erreurs"
      render 'new'
    end
  end

  def edit
    @draft = Article.find(params[:id])

    unless user_current.id != @draft.user_id or user_current.role == 'admin'
      flash[:error] = "Cet article ne vous appartient pas"
      redirect_to '/'
    end
  end

  def update
    @draft = Article.friendly.find(params[:id])

    if @draft.update(article_params)
      @draft.update_attributes(:user_id => user_current.id)
      flash[:success] = "L'article a bien été mis à jour"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def delete
    @article = Article.find(params[:id])
    if user_current.id != @article.user_id
      flash[:success] = "Ce article ne vous appartient pas"
      redirect_to articles_path
    end
    Article.destroy(params[:id])
    flash[:success] = "L'article a bien été supprimé"
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :slug, :content, :user_id, :published)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h2>Editer l'article</h2>

<%= form_for @draft, url: edit_article_path do |f| %>
<% if @draft.errors.full_messages.first %>
  <div class="alert alert-warning">
    <% @draft.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </div>
<% end %>
  <div class="form-group">
    <%= f.label :title, 'Titre' %>
    <%= f.text_field :title, {:class => 'form-control'} %>
  </div>
  <%= f.hidden_field :slug %>
  <div class="form-group">
    <%= f.label :content, 'Contenu' %>
    <%= f.text_area :content, {:class => 'form-control'} %>
  </div>
  <% if user_current.role == 'admin' %>
    <div class="form-group">
      <%= f.label :published, 'En ligne ?' %>
      <%= f.check_box :published %>
      <span class="checkmark"></span>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.submit 'Editer', {:class => 'btn btn-success'} %>
  </div>
<% end %>

app/views/articles/index.html.erb
<h2 class="pull-left">Brouillon</h2>
<div class="pull-right">
  <%= link_to 'Ajouter un brouillon', new_article_path, {:class => 'btn btn-success'} %>
</div>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Titre de l'article</th>
      <th></th>
      <th>Publié</th>
    </tr>
  </thead>
  <tbody>
    <% @draft.each do |draft| %>
      <tr>
        <td><%= draft.title %></td>
        <td>
          <%= link_to 'Editer', edit_article_path(draft.id) %>
          <% if draft.published == 1 %>
             - <%= link_to 'Voir', article_path(draft.slug, draft.id) %>
          <% end %>
          - <%= link_to 'Supprimer', delete_article_path(draft), method: :delete, data: {confirm: 'Vous êtes sur ?'} %>
        </td>
        <td>
          <% if draft.published == 1 %>
            <div class="text-success">Oui</div>
          <% else %>
            <div class="text-danger">Non</div>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tr>
  </tbody>
</table>

app/views/articles/new.html.erb
<h2>Ajouter un brouillon</h2>

<%= form_for @draft, url: new_article_path do |f| %>
  <% if @draft.errors.full_messages.first %>
    <div class="alert alert-warning">
      <% @draft.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title, 'Titre' %>
    <%= f.text_field :title, {:class => 'form-control', :value => 'Brouillon'} %>
  </div>
  <div class="form-group">
    <%= f.label :content, 'Contenu' %>
    <%= f.text_area :content, {:class => 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.submit 'Envoyer', {:class => 'btn btn-success'} %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<% if current_user %>
  <% if user_current.id == @article.user_id %>
    <%= link_to 'Editer', edit_article_path %>
  <% end %>
<% end %>

<div class="content">
  <%= Markdown.new(@article.content).to_html.html_safe %>
</div>