config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index', as: :home

  get '/blog/:slug-:id', to: 'articles#show', as: :article

  match "/login", to: 'user#login', as: 'login_user', via: [:get, :post]
  get '/logout', to: 'user#logout', as: 'logout_user'
  get '/register', to: 'user#new', as: 'new_user'
  post '/register', to: 'user#create'

  get '/draft', to: 'articles#index', as: :articles
  get '/draft/new', to: 'articles#new', as: :new_article
  post '/draft/new', to: 'articles#create'

  get '/draft/:id/edit', to: 'articles#edit', as: :edit_article
  patch '/draft/:id/edit', to: 'articles#update'
  get '/draft/:id/delete', to: 'articles#delete', as: :delete_article
end

app/models/user.rb
require 'digest/sha1'
class User < ApplicationRecord
  has_merit


  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true

  before_create :crypter_pass

  def self.authenticate username, password
    user = find_by(username: username)
    return nil if user and user.password != User.crypter(password)
    user
  end

  private
    def crypter_pass
      self.password = User.crypter(password)
    end

    def self.crypter pass
      Digest::MD5.hexdigest(pass)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_user_path
    else
      flash[:error] = "Corriger vos erreurs"
      render 'new'
    end
  end

  def login
    if params[:username]
      username, password = params[:username], params[:password]

      @user = User.authenticate username, password

      if @user
        session[:user] = @user
        flash[:success] = "Connecté"

        redirect_to '/'
      else
        flash[:error] = "Nom d'utilisateur ou mot de passe incorrect"
      end
    end
  end

  def logout
    session[:user] = nil
    redirect_to new_user_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users/user_helper.rb
module Users::UserHelper
end

app/views/user/login.html.erb
<h2>Se connecter</h2>

<%= form_for login_user_path do |f| %>
  <div class="form-group">
    <%= f.label :username, "Nom d'utilisateur" %>
    <%= f.text_field :username, :class => 'form-control', :name => 'username' %>
  </div>
  <div class="form-group">
    <%= f.label :password, "Mot de passe" %>
    <%= f.password_field :password, :class => 'form-control', :name => 'password' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Se connecter', :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/user/new.html.erb
<h2>S'inscrire</h2>

<%= form_for @user, url: register_path do |f| %>
  <% if @user.errors.full_messages.first %>
    <div class="alert alert-warning">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :username, "Nom d'utilisateur" %>
    <%= f.text_field :username, {:class => 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :email, "Email" %>
    <%= f.text_field :email, {:class => 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :password, "Mot de passe" %>
    <%= f.password_field :password, {:class => 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.submit 'Créer', :class => 'btn btn-success' %>
  </div>
<% end %>