config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index', as: :home

  get '/blog/:slug-:id', to: 'articles#show', as: :article

  match "/login", to: 'user#login', as: 'login_user', via: [:get, :post]
  get '/logout', to: 'user#logout', as: 'logout_user'
  get '/register', to: 'user#new', as: 'new_user'
  post '/register', to: 'user#create'

  get '/draft', to: 'articles#index', as: :articles
  get '/draft/new', to: 'articles#new', as: :new_article
  post '/draft/new', to: 'articles#create'

  get '/draft/:id/edit', to: 'articles#edit', as: :edit_article
  patch '/draft/:id/edit', to: 'articles#update'
  get '/draft/:id/delete', to: 'articles#delete', as: :delete_article
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Site</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'app', 'font-awesome' %>
    <style>
      .welcome span {
        position: absolute;
        line-height: 60px;
        left: -50px;
        float: left;
        color: #FFF;
      }
      .welcome a {
        float: right;
      }
    </style>
    <% if current_user %>
      <%= stylesheet_link_tag 'user' %>
    <% end %>
  </head>

  <body>
    <%= render 'elements/header' %>
    <div class="site-container">
      <div class="container">
        <% if flash[:success] %>
          <div class="alert alert-success">
            <%= raw flash[:success] %>
          </div>
        <% end %>
        <% if flash[:error] %>
          <div class="alert alert-danger">
            <%= raw flash[:error] %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  <% if current_user %>
    <div class="user_trigger-menu">
      <div class="top">
        <div class="avatar">
          <img src="https://www.grafikart.fr/uploads/avatars/default.png" alt="Default">
        </div>
        <nav>
          <a href="#">
            <i class="fa fa-user icon"></i>
            Mon compte
          </a>
          <a href="<%= url_for articles_path %>">
            <i class="fa fa-inbox icon"></i>
            Mes articles
          </a>
        </nav>
      </div>
      <div class="bottom">
        <a href="<%= url_for logout_user_path %>">
          <i class="fa fa-sign-out icon logout"></i>
          Se déconnecter
        </a>
      </div>
    </div>
  <% end %>
  </body>
  <%= javascript_include_tag 'jquery', 'mdeditor.min', 'application' %>
</html>